/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package business.management.system;

import business.management.system.APImodels.Quote;
import business.management.system.APImodels.Stock;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

/**
 *
 * @author saketh
 */
public class Chart extends javax.swing.JFrame {

    /**
     * Creates new form Chart
     */
    public Chart() throws SQLException {
        initComponents();
        JFreeChart barChart = ChartFactory.createBarChart(
         "Stock quote",           
         "Category",            
         "Score",            
         createDataset(),          
         PlotOrientation.VERTICAL,           
         true, true, false);
        JPanel panel = new JPanel();
        ChartPanel chartPanel = new ChartPanel( barChart );        
        chartPanel.setPreferredSize(new java.awt.Dimension( 560 , 367 ) );        
        panel.add(chartPanel);
        JFreeChart pieChart = ChartFactory.createPieChart(
         "Completed projects",           
         createPieDataset()     
         );
        ChartPanel chartPanel1 = new ChartPanel( pieChart );        
        chartPanel.setPreferredSize(new java.awt.Dimension( 560 , 367 ) );       
        panel.add(chartPanel1);
        setContentPane(panel); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Chart().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Chart.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private CategoryDataset createDataset() {
      final String change = "change";        
      final String price = "price in usd";        
      final String dl = "days low";        
      final String dh = "days high";        
      final DefaultCategoryDataset dataset = 
      new DefaultCategoryDataset( );             
       Call<Stock> call = APIClient.getAPI().getStocks();
        call.enqueue(new Callback<Stock>() {

            @Override
            public void onResponse(Call<Stock> call, Response<Stock> rspns) {
                for(Quote quote : rspns.body().getQuery().getResults().getQuote()){
                    dataset.addValue(Double.parseDouble(quote.getChange()), quote.getName(), change);
                    dataset.addValue(Double.parseDouble(quote.getLastTradePriceOnly()), quote.getName(), price);
                    dataset.addValue(Double.parseDouble(quote.getDaysLow()), quote.getName(), dl);
                    dataset.addValue(Double.parseDouble(quote.getDaysHigh()), quote.getName(), dh);
                }
            }

            @Override
            public void onFailure(Call<Stock> call, Throwable thrwbl) {
                
            }
        });
      return dataset; 
    }

    private PieDataset createPieDataset() throws SQLException {
         DefaultPieDataset dataset = new DefaultPieDataset( );
        ResultSet rs = Methods.getTeamProjectCount();
        while(rs.next()){
            int id = rs.getInt("team_id");
            int count = rs.getInt(2);
            dataset.setValue("team id: " + id, new Double(count));
        }
        return dataset;
    }
    
}
